beat/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponseRedirect
from work_management import views as customer_views

urlpatterns = [
    path('', lambda r: HttpResponseRedirect('master/')),
    path('admin/', admin.site.urls),
    path('login/', customer_views.user_login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('grappelli/', include('grappelli.urls')),
    path('master/', include('master.urls')),
    path('order/', include('order.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

master/urls.py
from django.urls import path, include
from master import views

urlpatterns = [
    path(
        "auto-complete/",
        include("master.auto_complete_urls")
    ),
    path(
        "edit/",
        include("master.edit_urls")
    ),
    path(
        "town/",
        views.TownView.as_view(),
        name="town_view"
    ),
    path(
        "",
        views.master_home,
        name="master_home"
    ),
    path(
        "company/",
        views.CompanyView.as_view(),
        name="company"
    ),
    path(
        "state/",
        views.StateView.as_view(),
        name="state"
    ),
    path(
        "district/",
        views.DistrictView.as_view(),
        name="district"
    ),
    path(
        "productgroup/",
        views.ProductGroupView.as_view(),
        name="product_group"
    ),
    path(
        "product/",
        views.ProductView.as_view(),
        name="product"
    ),
    path(
        "designation/",
        views.DesignationView.as_view(),
        name="designation"
    ),
    path(
        "employee/",
        views.EmployeeView.as_view(),
        name="employee"
    ),
    path(
        "distributor/",
        views.DistributorView.as_view()
    ),
    path(
        "unit/",
        views.UnitView.as_view()
    ),
    path(
        "companykeyperson/",
        views.CompanyKeyPersonView.as_view()
    )
]

master/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import validate_email, RegexValidator
from django.utils.safestring import mark_safe


class DatesManager(models.Model):
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)

    def __str__(self):
        if self.end_date:
            return self.start_date.strftime("%d-%b-%Y") \
                + " to " + self.end_date.strftime("%d-%b-%Y")
        else:
            return self.start_date.strftime("%d-%b-%Y") \
                + " to None"


class TaxManager(models.Model):
    tax_rate = models.FloatField()
    wef_date = models.DateField()

    def __str__(self):
        return str(self.tax_rate) + " on " + self.wef_date.strftime("%d-%b-%Y")


class State(models.Model):
    """
    State Table
    """
    name = models.CharField(max_length=255, unique=True)
    code = models.CharField(max_length=2, unique=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name


class District(models.Model):
    """
    District Table
    """
    name = models.CharField(max_length=255)
    state = models.ForeignKey(State, models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name + ', ' + self.state.name


class Town(models.Model):
    """
    Town Table
    """
    name = models.CharField(max_length=255)
    state = models.ForeignKey(State, on_delete=models.PROTECT)
    district = models.ForeignKey(District, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name


class Unit(models.Model):
    """
    Unit Table
    """
    code = models.CharField(max_length=3, unique=True)
    name = models.CharField(max_length=255, unique=True)
    decimal_places = models.CharField(max_length=255)
    weight_of_single_unit = models.DecimalField(
        default=0,
        max_digits=10,
        decimal_places=3
    )
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name


class ProductGroup(models.Model):
    """
    Product Table
    """
    code = models.CharField(max_length=4, unique=True)
    name = models.CharField(max_length=255)
    manual_rate = models.BooleanField(default=False)
    manual_MRP = models.BooleanField(default=False)
    enable_SPD = models.BooleanField(default=False)
    launch_discontinuation_date = models.ManyToManyField(
        DatesManager,
        blank=True,
        related_name="l_d_date"
    )
    tax = models.ManyToManyField(TaxManager, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name

    @property
    def launch_dates(self):
        return mark_safe(
            ',<br/>'.join(
                [str(date) for date in self.launch_discontinuation_date.all()]
            )
        )

    @property
    def tax_wef(self):
        return mark_safe(',<br/>'.join([str(tax) for tax in self.tax.all()]))


class Product(models.Model):
    name = models.CharField(max_length=255)
    group = models.ForeignKey(ProductGroup, on_delete=models.PROTECT)
    short_code = models.CharField(max_length=10)
    unit = models.ForeignKey(Unit, models.PROTECT)
    content = models.CharField(max_length=255)
    current_case_size = models.IntegerField(default=0)
    packaging_charges = models.IntegerField(default=0)
    launch_discontinuation_date = models.ManyToManyField(
        DatesManager,
        blank=True
    )

    base_for_mrp = models.BooleanField(default=False)
    mrp_round = models.CharField(max_length=255, choices=(
        ("2 Decimals", "2 Decimals"),
        ("Nearest Upper", "Nearest Upper"),
        ("Nearest Lower", "Nearest Lower"),
    ), default="2 Decimals")
    default_mrp = models.FloatField(default=0.0)

    base_for_rate = models.BooleanField(default=False)
    rate_round = models.CharField(max_length=255, choices=(
        ("2 Decimals", "2 Decimals"),
        ("Nearest Upper", "Nearest Upper"),
        ("Nearest Lower", "Nearest Lower"),
    ), default="2 Decimals")
    default_rate = models.FloatField(default=0.0)

    formula_for_mrp = models.TextField(blank=True)
    formula_for_rate = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name


class Designation(models.Model):
    code = models.CharField(max_length=3, unique=True)
    name = models.CharField(max_length=255, unique=True)
    work_area = models.CharField(max_length=255, choices=(
        ('office', 'Office'),
        ('field', 'Field'),
        ('both', 'Both')
    ))
    reporting_designation = models.ForeignKey(
        "Designation",
        models.PROTECT,
        blank=True,
        null=True
    )
    is_master = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name


def upload_user_photo_to(instance, filename):
    return "images/{0}/{1}".format(instance.name, filename)


def upload_user_document_to(instance, filename):
    return "documents/employee/{0}/{1}".format(instance.name, filename)


class Employee(models.Model):
    name = models.CharField(max_length=255)
    photo = models.ImageField(
        upload_to=upload_user_photo_to,
        blank=True,
        null=True
    )
    address = models.TextField()
    state = models.ForeignKey(State, models.PROTECT)
    district = models.ForeignKey(District, models.PROTECT)
    town = models.ForeignKey(
        Town,
        models.PROTECT,
        related_name="town_name"
    )
    pin_code = models.IntegerField(
        validators=[
            RegexValidator(
                regex=r'^[0-9]{6}',
                message="Pincode should consist of 6 digits"
            )
        ]
    )
    personal_mobile_number = models.CharField(
        max_length=10,
        blank=True,
        null=True,
        validators=[
            RegexValidator(
                regex=r'^[0-9]{10}$',
                message="Phone Number should be of 10 digits",
                code="invalid_phone_number_1"
            )
        ]
    )
    company_mobile_number = models.CharField(
        max_length=10,
        blank=True,
        null=True,
        validators=[
            RegexValidator(
                regex=r'^[0-9]{10}$',
                message="Phone Number should be of 10 digits",
                code="invalid_phone_number_2"
            )
        ]
    )
    email_id = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        validators=[
            validate_email
        ]
    )
    blood_group = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        choices=(
            ('A+', 'A+'),
            ('B+', 'B+'),
            ('O+', 'O+'),
            ('AB+', 'AB+'),
            ('A-', 'A-'),
            ('B-', 'B-'),
            ('O-', 'O-'),
            ('AB-', 'AB-')
        )
    )
    designation = models.ForeignKey(Designation, models.PROTECT)
    call_code = models.CharField(
        max_length=4,
        unique=True
    )
    # Emergency
    emergency_contact_name = models.CharField(max_length=255)
    emergency_contact_mobile_number = models.CharField(
        max_length=10,
        blank=True,
        null=True,
        validators=[
            RegexValidator(
                regex=r'^[0-9]{10}$',
                message="Phone Number should be of 10 digits",
                code="invalid_phone_number_2"
            )
        ]
    )
    emergency_contact_relation = models.CharField(max_length=255)

    pan_number = models.CharField(max_length=10, validators=[
        RegexValidator(
            regex=r'^[A-Z]{3}[P][A-Z]{1}[0-9]{4}[A-Z]{1}$',
            message="Invalid Pan Number",
            code="invalid_pan"
        )
    ])
    pan_attachment = models.ImageField(
        upload_to=upload_user_document_to,
        blank=True,
        null=True
    )

    aadahar_number = models.CharField(max_length=14, validators=[
        RegexValidator(
            regex=r'^\d{4}\d{4}\d{4}$',
            message="Invalid Aadahar Card",
            code="invalid_aadhar"
        )
    ])
    aadahar_attachement = models.ImageField(
        upload_to=upload_user_document_to,
        blank=True,
        null=True
    )

    pf_no = models.CharField(max_length=255, blank=True, null=True)
    esic_no = models.CharField(max_length=255, blank=True, null=True)

    bank_name = models.CharField(max_length=255)
    account_number = models.CharField(max_length=255)
    isfc_code = models.CharField(max_length=255)
    branch = models.CharField(max_length=255)

    dob = models.DateField()
    joining_leaving_date = models.ManyToManyField(
        DatesManager,
        blank=True
    )
    cv = models.ImageField(
        upload_to=upload_user_document_to,
        blank=True,
        null=True
    )
    # Headquerter
    headquarter_state = models.ForeignKey(
        State,
        models.PROTECT,
        related_name="headquarter_state"
    )
    headquarter_district = models.ForeignKey(
        District,
        models.PROTECT,

master/templates/distributor/add_distributor.html
{% extends 'base.html' %}
{# Don't forget that one ! #}
{% load static %}
{% block title %}
    Add Distributor
{% endblock title %}
{% block page_title %}Masters{% endblock page_title %}

{% block container %}
    <h3>Add Distributor</h3>
    <hr>
    {% include 'partial/form.html' with date1="Date of Appointment" date2="Date of Cease" %}
{% endblock container %}

{% block footer %}
{{ form.media }}
<script>
    document.querySelector("#id_gst_number").addEventListener("change", function(){
        document.querySelector("#id_pan_number").value = document.querySelector("#id_gst_number").value.slice(2,12)
    });

    $(document).ready(function() {
        var direct = document.querySelector("#id_direct_from_company");
        var local = document.querySelector("#id_local_selling").parentElement;
        var onward = document.querySelector("#id_onward_supply").parentElement;
        if (!direct.checked) {
            $(local).hide();
            $(onward).hide();
        }

        direct.addEventListener("change", function(){
            if (direct.checked) {
                $(local).fadeIn();
                $(onward).fadeIn();
            } else {
                $(local).fadeOut();
                $(onward).fadeOut();
            }
        })
    })
</script>
{% endblock %}

master/templates/distributor/display_distributor.html
{% extends 'base.html' %}
{% block title %}
    Distributor List
{% endblock title %}
{% block page_title %}Masters{% endblock page_title %}
{% block container %}
    {% include "partial/table.html" with page_name="Distributor" %}
{% endblock container %}

{% block footer %}
<style>
    table {
        margin: 0 !important;
    }
</style>
{% endblock %}

master/templates/distributor/edit_distributor.html
{% extends 'base.html' %}
{# Don't forget that one ! #}
{% load static %}
{% block title %}
    Edit Distributor
{% endblock title %}
{% block page_title %}Masters{% endblock page_title %}

{% block container %}
    <h3>Edit Distributor</h3>
    <hr>
    {% include 'partial/form.html' with date1="Date of Appointment" date2="Date of Cease" %}
{% endblock container %}

{% block footer %}
{{ form.media }}
<script>
    document.querySelector("#id_gst_number").addEventListener("change", function(){
        document.querySelector("#id_pan_number").value = document.querySelector("#id_gst_number").value.slice(2,12)
    });

    $(document).ready(function() {
        var direct = document.querySelector("#id_direct_from_company");
        var local = document.querySelector("#id_local_selling").parentElement;
        var onward = document.querySelector("#id_onward_supply").parentElement;
        if (!direct.checked) {
            $(local).hide();
            $(onward).hide();
        }

        direct.addEventListener("change", function(){
            if (direct.checked) {
                $(local).fadeIn();
                $(onward).fadeIn();
            } else {
                $(local).fadeOut();
                $(onward).fadeOut();
            }
        })
    })
</script>
{% endblock %}