beat/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponseRedirect
from work_management import views as customer_views

urlpatterns = [
    path('', lambda r: HttpResponseRedirect('master/')),
    path('admin/', admin.site.urls),
    path('login/', customer_views.user_login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('grappelli/', include('grappelli.urls')),
    path('master/', include('master.urls')),
    path('order/', include('order.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/urls.py
from django.urls import path, include
from order import views

urlpatterns = [
    path('', views.OrderView.as_view()),
    path(
        "auto-complete/",
        include("order.auto_complete_urls")
    ),
    path(
        "order_number/",
        views.generate_order_number
    ),
    path(
        "edit/<int:pk>/",
        views.OrderEditView.as_view(),
        name="edit_order"
    ),
    path(
        "update_satus/<int:pk>/<int:type>",
        views.update_order_status,
        name="update_order_status"
    ),
    path(
        "generate_pdf/<int:pk>",
        views.generate_pdf,
        name="order_pdf"
    ),
    path(
        "product_detail/<int:pk>",
        views.get_product_details
    )
]

order/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.conf import settings
from django.utils.safestring import mark_safe
from master import models as master_models


class SpecialInstruction(models.Model):
    content = models.TextField()

    def __str__(self):
        return self.content


class OrderProductRow(models.Model):
    product = models.ForeignKey(master_models.Product, models.PROTECT)
    product_quantity = models.IntegerField()
    product_cases = models.IntegerField()
    product_weight = models.FloatField()
    product_mrp = models.FloatField()

    def __str__(self):
        return self.product.name


class Order(models.Model):
    product_group = models.ForeignKey(
        master_models.ProductGroup,
        models.PROTECT
    )
    company = models.ForeignKey(master_models.Company, models.PROTECT)
    order_date = models.DateField(auto_now=True)
    order_number = models.CharField(max_length=255)
    distributor = models.ForeignKey(master_models.Distributor, models.PROTECT)
    town = models.ForeignKey(master_models.Town, models.PROTECT)
    bar_rate = models.FloatField()
    bill_rate = models.FloatField()
    s_p_d = models.FloatField()
    m_r_p = models.FloatField()
    total_quantity = models.IntegerField()
    total_cases = models.IntegerField()
    total_weight = models.FloatField()
    special_instruction = models.TextField()

    products = models.ManyToManyField(
        OrderProductRow,
        blank=True
    )

    # Dispatch To
    dispatch_firm_name = models.CharField(
        max_length=255,
        verbose_name="Firm Name"
    )
    dispatch_address = models.TextField()
    dispatch_gst_number = models.CharField(
        max_length=255,
        validators=[
            RegexValidator(
                regex=r'^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$'
            )
        ]
    )

    status = models.CharField(
        max_length=255,
        choices=(
            ("Pending", "Pending"),
            ("Processing", "Processing"),
            ("Delivered", "Delivered")
        ),
        default="Pending"
    )

    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, models.CASCADE)

    def __str__(self):
        return "Order of ("\
            + self.distributor.firm_name + ") "\
            + self.town.name

    @property
    def delete_order(self):
        if self.status == "Pending":
            return mark_safe("""<a href='/order/delete/{0}'>
                <span class="delete-icon" uk-icon="trash"></span>
            </a>""".format(self.id))
        return ""

    @property
    def edit_order(self):
        if self.status == "Pending":
            return mark_safe("""<a href='/order/edit/{0}'>
                <span uk-icon="pencil"></span>
            </a>""".format(self.id))
        return ""

    @property
    def update_status_handler(self):
        string = ""
        if self.status != "Delivered":
            string += """
                <a href='/order/update_satus/{0}/0'>
                    <span uk-icon="push"></span>
                </a>
            """
        if self.status != "Pending":
            string += """
                <a href='/order/update_satus/{0}/1'>
                    <span uk-icon="pull"></span>
                </a>
            """
        return mark_safe(string.format(self.id))

order/forms.py
from django import forms
from djangoformsetjs.utils import formset_media_js
from django.forms import BaseFormSet
from django.utils.timezone import now
from order import models
from master import models as master_models
from master.forms import RelatedFieldWidgetCanAdd, \
    MultipleRelatedFieldWidgetCanAdd


class OrderForm(forms.ModelForm):

    class Meta:
        model = models.Order
        fields = ('__all__')


class ProductFormSet(BaseFormSet):
    def clean(self):
        if any(self.errors):
            return


class ProductRowForm(forms.ModelForm):

    class Meta:
        model = models.OrderProductRow
        fields = ('__all__')
        widgets = {
            'product':
            RelatedFieldWidgetCanAdd(
                related_model=master_models.Product,
                url='/order/auto-complete/product/',
                related_url='/master/product/?add',
                forward=['product_group']
            ),
        }

    class Media(object):
        js = formset_media_js


class OrderFormPart1(forms.ModelForm):

    date = forms.DateField()

    class Meta:
        model = models.Order
        fields = (
            'product_group', 'company', 'date', 'order_number', 'distributor',
            'town', 'bar_rate', 'bill_rate', 's_p_d', 'm_r_p',
        )
        widgets = {
            'product_group':
            RelatedFieldWidgetCanAdd(
                related_model=master_models.ProductGroup,
                url='/order/auto-complete/product-group/',
                related_url='/master/productgroup/?add'
            ),
            'company':
            RelatedFieldWidgetCanAdd(
                related_model=master_models.Company,
                url='/order/auto-complete/company/',
                related_url='/master/company/?add',
                forward=['product_group']
            ),
            'distributor':
            RelatedFieldWidgetCanAdd(
                related_model=master_models.Distributor,
                url='/order/auto-complete/distributor/',
                related_url='/master/distributor/?add',
                forward=['product_group', 'company']
            ),
            'town':
            RelatedFieldWidgetCanAdd(
                related_model=master_models.Town,
                url='/order/auto-complete/town/',
                related_url='/master/town/?add',
            ),
        }


class OrderFormPart2(forms.ModelForm):

    class Meta:
        model = models.Order
        fields = (
            'total_quantity', 'total_cases', 'total_weight',
            'special_instruction', 'dispatch_firm_name', 'dispatch_address',
            'dispatch_gst_number', 'status'
        )

order/views.py
from django.shortcuts import render, HttpResponse, redirect, Http404
from django.http import JsonResponse
from django.forms import formset_factory
from django.views import View
from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa
from django_tables2 import RequestConfig
from django_tables2.export.export import TableExport
from order import forms, models, tables, filters
from order.utils import generate_product_dict
from master import models as master_models


class OrderView(View):

    def get(self, request):
        return self.add(request) if 'add' in request.GET \
            else self.display(request)

    def add(self, request):
        part_1_form = forms.OrderFormPart1()
        part_2_form = forms.OrderFormPart2()
        product_row_form = formset_factory(
            forms.ProductRowForm,
            extra=1,
            can_delete=True,
            validate_min=True,
            formset=forms.ProductFormSet
        )(prefix='product_row')
        context = {
            'form': part_1_form,
            'form2': part_2_form,
            'product_row_form': product_row_form
        }
        return render(request, "order/add_order.html", context)

    def display(self, request):
        order_filter = filters.OrderFilter(request.GET)
        order_table = tables.OrderTable(order_filter.qs)
        RequestConfig(
            request, paginate={
                'per_page': 50
            }).configure(order_table)
        context = {'table': order_table, 'filter': order_filter}

        export_format = request.GET.get('_export', None)
        if TableExport.is_valid_format(export_format):
            exporter = TableExport(export_format, order_table)
            return exporter.response('table.{}'.format(export_format))

        return render(request, "order/display_order.html", context)

    def post(self, request):
        post_data = request.POST.copy()
        post_data['added_by'] = request.user.id
        form = forms.OrderForm(post_data)
        part_1_form = forms.OrderFormPart1(request.POST)
        part_2_form = forms.OrderFormPart2(request.POST)
        product_row_form = formset_factory(
            forms.ProductRowForm,
            extra=1,
            can_delete=True,
            validate_min=True,
            formset=forms.ProductFormSet
        )(request.POST, prefix='product_row')

        form_error = False
        if form.is_valid() and product_row_form.is_valid():
            for product in product_row_form:
                if not product.is_valid():
                    form_error = True

            if not form_error:
                order = form.save()

                for product in product_row_form:
                    new_product = product.save()
                    order.products.add(new_product)
                return redirect('/master/')
        context = {
            'form': part_1_form,
            'form2': part_2_form,
            'product_row_form': product_row_form
        }
        return render(request, "order/add_order.html", context)


class OrderEditView(View):

    def getObject(self, pk):
        try:
            return models.Order.objects.get(id=pk)
        except:
            raise Http404

    def get(self, request, pk):
        obj = self.getObject(pk)
        part_1_form = forms.OrderFormPart1(instance=obj)
        part_2_form = forms.OrderFormPart2(instance=obj)
        product_row_form = formset_factory(
            forms.ProductRowForm,
            extra=1,
            can_delete=True,
            validate_min=True,
            formset=forms.ProductFormSet
        )(generate_product_dict(obj, 'products'), prefix='product_row')

        for each_err in product_row_form.errors:
            if 'product' in each_err:
                each_err['product'] = ""
        context = {
            'form': part_1_form,
            'form2': part_2_form,
            'product_row_form': product_row_form
        }
        return render(request, "order/add_order.html", context)

    def post(self, request, pk):
        obj = self.getObject(pk)
        post_data = request.POST.copy()
        post_data['added_by'] = request.user.id

        form = forms.OrderForm(post_data, instance=obj)
        part_1_form = forms.OrderFormPart1(request.POST)
        part_2_form = forms.OrderFormPart2(request.POST)
        product_row_form = formset_factory(
            forms.ProductRowForm,
            extra=1,
            can_delete=True,
            validate_min=True,
            formset=forms.ProductFormSet
        )(request.POST, prefix='product_row')

        form_error = False
        if form.is_valid() and product_row_form.is_valid():
            for product in product_row_form:
                if not product.is_valid():
                    form_error = True

            if not form_error:
                order = form.save()
                order.products.clear()

                for product in product_row_form:
                    new_product = product.save()
                    order.products.add(new_product)
                return redirect('/order/')
        context = {
            'form': part_1_form,
            'form2': part_2_form,
            'product_row_form': product_row_form
        }
        return render(request, "order/add_order.html", context)


def generate_pdf(request, pk):
    order = models.Order.objects.get(id=pk)
    return render_to_pdf("order/pdf.html", {'order': order})


def generate_order_number(request):
    pg_code = master_models.ProductGroup.objects.get(id=request.GET['p'])
    c_code = master_models.Company.objects.get(id=request.GET['c'])
    order = models.Order.objects.order_by('-pk').count()
    return HttpResponse("{0}/{1}/{2}".format(
        pg_code.code,
        c_code.code,
        order + 1
    ))


def update_order_status(request, pk, type):
    status = {
        "Pending": "Processing",
        "Processing": "Delivered",
    } if type == 0 else {
        "Processing": "Pending",
        "Delivered": "Processing",
    }

    order = models.Order.objects.get(id=pk)
    order.status = status[order.status]
    order.save()
    return redirect("/order/")


def get_product_details(request, pk):
    product = master_models.Product.objects.get(id=pk)
    pro_obj = {
        "name": product.name,
        "casses": product.current_case_size,
        "content": product.content,
        "weight": product.unit.weight_of_single_unit,
        "decimal": product.unit.decimal_places
    }
    if product.base_for_mrp:
        pro_obj['mrp'] = product.default_mrp
    if product.base_for_rate:
        pro_obj['rate'] = product.default_rate
    return JsonResponse(pro_obj, safe=False)


def render_to_pdf(path: str, params: dict):
    template = get_template(path)
    html = template.render(params)
    response = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), response)
    if not pdf.err:
        return HttpResponse(response.getvalue(), content_type='application/pdf')
    return HttpResponse("Error Rendering PDF", status=400)

order/templates/order/add_order.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Add Order
{% endblock title %}
{% block page_title %}Orders{% endblock page_title %}

{% block container %}
    <h3>Add Order</h3>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% include 'order_partial/form.html' %}
        {% include 'order_partial/product_row_form.html' %}
        <h3>Total</h3>
        {% include 'order_partial/form.html' with form=form2%}
        <button class="uk-button uk-button-default uk-margin primary">
            Submit
        </button>
    </form>
{% endblock container %}

{% block footer %}
{{ form.media }}
<script>
    var total_quantity = document.querySelector("#id_total_quantity")
    var total_cases = document.querySelector("#id_total_cases")
    var total_weight = document.querySelector("#id_total_weight")
    var date = document.querySelector("#id_date")
    var orderNumber = document.querySelector("#id_order_number")
    var company = document.querySelector("#id_company")
    var product_group = document.querySelector("#id_product_group")

    total_quantity.setAttribute("readonly", "");
    total_cases.setAttribute("readonly", "");
    total_weight.setAttribute("readonly", "");
    date.setAttribute("readonly", "");
    orderNumber.setAttribute("readonly", "")
    date.type="date"
    date.valueAsDate = new Date();

    var formCount = -1;
    var total_quantity_value = 0;
    var total_cases_value = 0;
    var total_weight_value = 0;


    function formAdded() {
        formCount++;
        for (var i = 0; i <= formCount; i++) {
            document.querySelector(`#id_product_row-${i}-product_quantity`).addEventListener("change", function (e){qantityChanged(i-1)});
            document.querySelector(`#id_product_row-${i}-product_cases`).addEventListener("change", casesChanged);
            document.querySelector(`#id_product_row-${i}-product_weight`).addEventListener("change", weightChanged);
            $(`#select2-id_product_row-${i}-product-container`).on("DOMSubtreeModified", function (e){getProductdetail(i-1)})
        }
    }

    function formRemoved() {
        formCount--;
        qantityChanged();
        casesChanged ();
        weightChanged();
    }

    function qantityChanged (n) {
        total_quantity_value = 0;
        for (var i = 0; i <= formCount; i++) {
            total_quantity_value +=
                parseInt(document.querySelector(`#id_product_row-${i}-product_quantity`).value);
        }
        getProductdetail(n)
        total_quantity.value = total_quantity_value;
    }

    function casesChanged () {
        total_cases_value = 0;
        for (var i = 0; i <= formCount; i++) {
            total_cases_value +=
                parseInt(document.querySelector(`#id_product_row-${i}-product_cases`).value);
        }
        total_cases.value = total_cases_value;
    }

    function weightChanged () {
        total_weight_value = 0;
        for (var i = 0; i <= formCount; i++) {
            total_weight_value +=
                parseInt(document.querySelector(`#id_product_row-${i}-product_weight`).value);
        }
        total_weight.value = total_weight_value;
    }

    function getOrderNumber(e) {
        var c = company.value;
        var pg = product_group.value;
        if (c && pg) {
            $("#select2-id_product_group-container").off("DOMSubtreeModified")
            $("#select2-id_company-container").off("DOMSubtreeModified")

            $.get(`/order/order_number/?c=${c}&p=${pg}`, function(data) {
                orderNumber.value = data;
             })
             setTimeout(function() {
                 $("#select2-id_product_group-container").on("DOMSubtreeModified", getOrderNumber)
                 $("#select2-id_company-container").on("DOMSubtreeModified", getOrderNumber)
             }, 500)
        }
    }

    function getProductdetail(n) {
        p_id = $(`#id_product_row-${n}-product`).val()
        console.log(n, p_id)
        if (p_id) {
            $(`#select2-id_product_row-${n}-product-container`).off("DOMSubtreeModified")
            $.getJSON(`/order/product_detail/${p_id}`, function(data) {
                quantity = $(`#id_product_row-${n}-product_quantity`).val()
                casses = Number(quantity) / Number(data.casses)
                weight = Number(quantity) * data.content * data.weight
                $(`#id_product_row-${n}-product_cases`).val(casses)
                $(`#id_product_row-${n}-product_weight`).val(weight)
                $(`#id_product_row-${n}-product_mrp`).val(data.mrp)
                qantityChanged();
                casesChanged ();
                weightChanged();
            })
            setTimeout(function() {
                $(`#select2-id_product_row-${n}-product-container`).on("DOMSubtreeModified", function (e){getProductdetail(n)})
            }, 500)
        }
    }

    $(document).ready(function(){
        $("#select2-id_product_group-container").on("DOMSubtreeModified", getOrderNumber)
        $("#select2-id_company-container").on("DOMSubtreeModified", getOrderNumber)
    })
</script>
{% endblock %}

order/templates/order/display_order.html
{% extends 'base.html' %}
{% block title %}
    Order List
{% endblock title %}
{% block page_title %}Order{% endblock page_title %}
{% block container %}
    {% include "partial/table.html" with page_name="Order" %}
{% endblock container %}

{% block footer %}
<style>
    table {
        margin: 0 !important;
    }
</style>
{% endblock %}

order/templates/order/pdf.html
<html>
    <body>
        <div>
            <h1>{{order}}</h1>

            <div>
                <table>
                    <tr>
                        <th>Order To</th>
                        <th>Dispatch To</th>
                    </tr>
                    <tr>
                        <td>
                            Company Name : {{order.company.firm_name}}
                        </td>
                        <td>
                            Distributor Name : {{order.distributor.firm_name}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Company Address : {{order.company.address}}
                        </td>
                        <td>
                            Distributor Address : {{order.distributor.address}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            City Pin : {{order.company.pin_code}}
                        </td>
                        <td>
                            City Pin : {{order.distributor.pin_code}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            GSTIN : {{order.company.gst_number}}
                        </td>
                        <td>
                            GSTIN : {{order.distributor.gst_number}}
                        </td>
                    </tr>
                </table>
            </div>
            <h2>Product Group</h2>
            <div>
                <table>
                        <tr>
                            <th>Order Date</th>
                            <th>Co. Order No:</th>
                            <th>BILL</th>
                            <th>BAR</th>
                            <th>SPD</th>
                        </tr>
                        <tr>
                            <td>{{order.order_date}}</td>
                            <td>{{order.order_number}}</td>
                            <td>{{order.bill_rate}}</td>
                            <td>{{order.bar_rate}}</td>
                            <td>{{order.s_p_d}}</th>
                        </tr>
                </table>
            </div>
            <div>
                <table>
                    <tr>
                        <th>Sl</th>
                        <th colspan=2>Item</th>
                        <th>Pcs</th>
                        <th>C/s</th>
                        <th>MRP</th>
                    </tr>
                    {% for pr in order.products.all %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td colspan=2>{{pr}}</td>
                            <td>{{pr.product_quantity}}</td>
                            <td>{{pr.product_cases}}</td>
                            <td>{{pr.product_mrp}}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <th colspan=6>&nbsp;</th>
                    </tr>
                    <tr>
                        <th>Total Cases</th>
                        <td>{{order.total_cases}}</td>
                        <th>Total Wieght</th>
                        <td>{{order.total_weight}}</td>
                        <th>Total Pcs</th>
                        <td>{{order.total_quantity}}</td>
                    </tr>
                </table>
            </div>
            <div>
                <h3>Special Instruction</h3>
                {{order.special_instruction}}
            </div>
        </div>
    </body>
    <style>
        @media print, screen {
            table {
                margin: 5px;
                border-collapse: collapse;
                width: 100%;
            }
    
            tr {
                border-bottom: 1px solid black;
            }
            th, td {
                text-align: left;
                padding: 10px;
                border: 1px solid black;
                border-collapse: collapse;
            }
    
            h1, h2, h3 {
                text-align: center;
            }
        }
    </style>
</html>